Script ran at 2025-06-14 22:09:35.898467
'C:\Users\user\Documents\Power' is not recognized as an internal or external command,
operable program or batch file.
Price fetched successfully
Price fetched successfully
Loaded to db successfully
Traceback (most recent call last):
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\data_ingestion\etl.py", line 92, in <module>
    with open("C:/Users/user/Documents/Power BI Desktop/Projects/Crypto BI/logs/etl_log.txt", "a") as f:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:/Users/user/Documents/Power BI Desktop/Projects/Crypto BI/logs/etl_log.txt'
Script ran at 2025-06-14 23:00:12.373889

Script ran at 2025-06-14 23:15:40.291197

Script ran at 2025-06-15 00:04:29.080445

Script ran at 2025-06-15 00:15:07.212083

Script ran at 2025-06-15 00:19:27.100653

Script ran at 2025-06-15 00:30:07.052629

Script ran at 2025-06-15 00:34:27.484852

Script ran at 2025-06-15 00:49:27.044141

Script ran at 2025-06-15 06:21:27.524553

Script ran at 2025-06-15 06:34:29.295641

Script ran at 2025-06-15 06:49:31.414763

Script ran at 2025-06-15 07:04:38.381376

Script ran at 2025-06-15 07:19:48.577172

Script ran at 2025-06-15 07:34:40.911506

Script ran at 2025-06-15 07:49:31.014582

Script ran at 2025-06-15 08:04:34.299461

Script ran at 2025-06-15 08:19:31.470001

Script ran at 2025-06-15 08:34:32.272952

Script ran at 2025-06-15 08:49:30.445923

Script ran at 2025-06-15 09:04:29.866906

Traceback (most recent call last):
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\util\ssl_.py", line 480, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\util\ssl_.py", line 524, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\util\util.py", line 39, in reraise
    raise value
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
        self, url, f"Read timed out. (read timeout={timeout_value})"
    ) from err
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.coingecko.com', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\data_ingestion\etl.py", line 85, in <module>
    usd_raw = fetch_prices('usd')
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\data_ingestion\etl.py", line 16, in fetch_prices
    response = requests.get(url, params=params)
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\requests\adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.coingecko.com', port=443): Read timed out. (read timeout=None)
Traceback (most recent call last):
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\util\ssl_.py", line 480, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\util\ssl_.py", line 524, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\util\util.py", line 39, in reraise
    raise value
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
        self, url, f"Read timed out. (read timeout={timeout_value})"
    ) from err
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.coingecko.com', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\data_ingestion\etl.py", line 85, in <module>
    usd_raw = fetch_prices('usd')
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\data_ingestion\etl.py", line 16, in fetch_prices
    response = requests.get(url, params=params)
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\.venv\Lib\site-packages\requests\adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.coingecko.com', port=443): Read timed out. (read timeout=None)
Script ran at 2025-06-15 09:49:32.265585

Script ran at 2025-06-15 10:04:28.648045

Script ran at 2025-06-15 10:19:30.886497

Script ran at 2025-06-15 10:34:28.634889

Script ran at 2025-06-15 10:49:35.895581

Script ran at 2025-06-15 11:04:28.532811

Script ran at 2025-06-15 11:19:31.961952

Script ran at 2025-06-15 11:34:28.271922

Script ran at 2025-06-15 11:49:33.988342

Script ran at 2025-06-15 12:04:30.590997

Script ran at 2025-06-15 12:19:30.593159

Script ran at 2025-06-15 12:34:29.844421

Script ran at 2025-06-15 12:49:30.914056

Script ran at 2025-06-15 13:04:31.395072

Script ran at 2025-06-15 13:24:50.506451

Script ran at 2025-06-15 13:34:31.523033

Script ran at 2025-06-15 13:49:31.980940

Script ran at 2025-06-15 14:04:36.341296

Script ran at 2025-06-15 14:19:31.648478

Traceback (most recent call last):
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\data_ingestion\etl.py", line 89, in <module>
    transformed = transform_data(usd_raw, ngn_raw)
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\data_ingestion\etl.py", line 36, in transform_data
    'image_url': coin.get('image', {}).get('thumb'),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
Script ran at 2025-06-15 14:50:10.155928

Traceback (most recent call last):
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\data_ingestion\etl.py", line 111, in <module>
    load_to_postgres(transformed)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\Documents\Power BI Desktop\Projects\Crypto BI\data_ingestion\etl.py", line 64, in load_to_postgres
    cur.execute("""
    ~~~~~~~~~~~^^^^
                INSERT INTO coin_metadata (id, symbol, name, image_url)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                VALUES (%s, %s, %s, %s)
                ^^^^^^^^^^^^^^^^^^^^^^^
                ON CONFLICT (id) DO UPDATE SET
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                """, (row['id'], row['symbol'], row['name'], row['image_url']))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.SyntaxError: syntax error at end of input
LINE 5:                         
                                ^

Script ran at 2025-06-15 15:19:49.112401

Script ran at 2025-06-15 19:15:16.514774

Script ran at 2025-06-15 20:15:19.675515

Script ran at 2025-06-15 20:30:32.162610

Script ran at 2025-06-15 20:45:09.254143

Script ran at 2025-06-15 21:00:11.310786

Script ran at 2025-06-15 21:15:08.430054

Script ran at 2025-06-15 21:30:30.975052

Script ran at 2025-06-15 21:45:38.625319

Script ran at 2025-06-15 22:00:22.863896

Script ran at 2025-06-15 22:15:36.997298

Script ran at 2025-06-15 22:30:21.965874

Script ran at 2025-06-15 22:48:08.657617

Script ran at 2025-06-15 23:00:34.514003

Error: Failed to fetch prices from API
Traceback (most recent call last):
  File "C:\Users\user\Documents\Power BI Desktop\Projects\crypto_bi\data_ingestion\etl.py", line 89, in <module>
    transformed = transform_data(usd_raw, ngn_raw)
  File "C:\Users\user\Documents\Power BI Desktop\Projects\crypto_bi\data_ingestion\etl.py", line 28, in transform_data
    for coin in raw_data_usd:
                ^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
Script ran at 2025-06-15 23:31:29.007832

Script ran at 2025-06-15 23:46:16.115691

Script ran at 2025-06-16 00:12:51.097590

Script ran at 2025-06-16 00:15:05.968865

Script ran at 2025-06-16 00:30:43.633465

Script ran at 2025-06-16 00:47:00.841712

Script ran at 2025-06-16 01:00:23.575581

Script ran at 2025-06-16 01:15:29.523783

Script ran at 2025-06-16 01:30:05.777501

Script ran at 2025-06-16 01:45:06.003972

Script ran at 2025-06-16 02:00:05.285075

Script ran at 2025-06-16 02:15:16.682983

Script ran at 2025-06-16 02:30:06.534859

Script ran at 2025-06-16 06:51:58.021232

Script ran at 2025-06-16 07:00:15.600349

Script ran at 2025-06-16 07:15:16.256541

Script ran at 2025-06-16 07:46:56.419116

Script ran at 2025-06-16 08:00:50.039692

Script ran at 2025-06-16 08:15:25.890409

Script ran at 2025-06-16 09:02:14.819458

Script ran at 2025-06-16 09:15:58.839481

Script ran at 2025-06-16 09:31:20.597662

Script ran at 2025-06-16 09:45:23.078861

Script ran at 2025-06-16 10:00:34.875571

Script ran at 2025-06-16 10:15:35.350767

Script ran at 2025-06-16 10:30:24.811589

Script ran at 2025-06-16 10:45:21.459613

Script ran at 2025-06-16 11:00:24.551763

Script ran at 2025-06-16 11:15:36.514934

Script ran at 2025-06-16 11:30:22.379136

Script ran at 2025-06-16 11:45:19.052455

Script ran at 2025-06-16 12:00:47.417232

Script ran at 2025-06-16 12:15:34.284896

Script ran at 2025-06-16 13:05:08.588660

Script ran at 2025-06-16 13:16:13.819238

Script ran at 2025-06-16 13:30:31.280591

Script ran at 2025-06-16 13:45:18.273703

Script ran at 2025-06-16 14:00:56.598607

Script ran at 2025-06-16 14:15:19.750495

Script ran at 2025-06-16 14:30:33.969535

Script ran at 2025-06-16 15:28:58.772473

Script ran at 2025-06-16 15:30:17.489240

Script ran at 2025-06-16 15:45:29.777557

Script ran at 2025-06-16 16:00:37.899527

Script ran at 2025-06-16 16:15:18.452370

Script ran at 2025-06-16 16:38:46.819730

Script ran at 2025-06-16 16:45:35.492517

Script ran at 2025-06-16 17:00:23.719966

Script ran at 2025-06-16 17:15:16.705206

Script ran at 2025-06-16 17:31:48.657579

Script ran at 2025-06-16 17:45:07.145747

Script ran at 2025-06-16 18:00:06.955256

Script ran at 2025-06-16 19:10:17.975505

Script ran at 2025-06-16 19:24:01.447379

Script ran at 2025-06-16 19:30:15.818593

Script ran at 2025-06-16 19:45:31.542988

Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Traceback (most recent call last):
  File "C:\Users\user\Documents\Power BI Desktop\Projects\crypto_bi\data_ingestion\etl.py", line 89, in <module>
    transformed = transform_data(usd_raw, ngn_raw)
  File "C:\Users\user\Documents\Power BI Desktop\Projects\crypto_bi\data_ingestion\etl.py", line 25, in transform_data
    ngn_map = {coin['id']: coin for coin in raw_data_ngn}
                                            ^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
'Script ran at 2025-06-16 22:00:25.301634

Script ran at 2025-06-16 22:02:47.433902

Script ran at 2025-06-16 22:15:33.547366

Script ran at 2025-06-16 22:17:33.238126

Script ran at 2025-06-16 22:30:23.908088

Script ran at 2025-06-16 22:38:28.747638

Script ran at 2025-06-16 22:45:34.004999

Script ran at 2025-06-16 22:48:39.309418

Script ran at 2025-06-16 23:02:59.777301

Script ran at 2025-06-16 23:16:09.488240

Script ran at 2025-06-16 23:21:37.453204

Script ran at 2025-06-17 05:37:35.661001

Script ran at 2025-06-17 05:46:29.178413

Script ran at 2025-06-17 05:49:17.120547

Script ran at 2025-06-17 06:00:38.415659

Script ran at 2025-06-17 06:02:33.973409

Script ran at 2025-06-17 06:15:22.655602

Script ran at 2025-06-17 06:17:32.706162

Script ran at 2025-06-17 06:30:42.067036

Script ran at 2025-06-17 06:32:42.240121

Script ran at 2025-06-17 06:45:54.580058

Script ran at 2025-06-17 06:48:08.084609

Script ran at 2025-06-18 10:30:08.008294

Script ran at 2025-06-18 10:33:00.857690

Script ran at 2025-06-18 10:37:16.464073

Script ran at 2025-06-18 10:45:06.053278

Script ran at 2025-06-18 10:47:15.806579

Script ran at 2025-06-18 10:52:15.563332

Script ran at 2025-06-18 11:00:12.790863

Script ran at 2025-06-18 11:02:17.736159

Script ran at 2025-06-18 11:07:11.734432

Script ran at 2025-06-18 11:45:17.987121

Script ran at 2025-06-18 11:52:20.092654

Script ran at 2025-06-18 12:00:14.386833

Script ran at 2025-06-18 12:02:19.851953

Script ran at 2025-06-18 12:07:19.927385

Script ran at 2025-06-18 12:15:16.652591

Script ran at 2025-06-18 12:17:19.881297

Script ran at 2025-06-18 12:22:14.693411

Script ran at 2025-06-18 12:30:13.478224

Script ran at 2025-06-18 12:32:19.953445

Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Script ran at 2025-06-18 14:22:13.323556

Script ran at 2025-06-18 14:30:12.805810

Script ran at 2025-06-18 14:32:56.661285

Script ran at 2025-06-18 14:37:27.563652

Script ran at 2025-06-18 14:46:15.911276

Script ran at 2025-06-18 14:47:18.570705

Script ran at 2025-06-18 14:52:27.072000

Script ran at 2025-06-18 15:00:05.930954

Script ran at 2025-06-18 15:02:15.444677

Script ran at 2025-06-18 15:10:39.268277

Script ran at 2025-06-18 15:15:09.478929

Script ran at 2025-06-18 15:17:16.845339

Script ran at 2025-06-18 15:22:13.593296

Script ran at 2025-06-18 15:30:47.862708

Error: Failed to fetch prices from API
Script ran at 2025-06-18 15:37:13.049477

Script ran at 2025-06-18 15:45:08.964586

Script ran at 2025-06-18 15:47:18.725480

Script ran at 2025-06-18 15:54:52.012131

Script ran at 2025-06-18 16:00:08.485198

Script ran at 2025-06-18 16:02:20.987558

Script ran at 2025-06-18 16:07:14.526522

Script ran at 2025-06-18 16:15:38.660868

Script ran at 2025-06-18 16:17:19.241084

Script ran at 2025-06-18 16:22:11.164151

Script ran at 2025-06-18 16:30:08.417594

Script ran at 2025-06-18 16:32:17.428129

Script ran at 2025-06-18 16:37:15.558738

Script ran at 2025-06-18 16:45:07.258893

Script ran at 2025-06-18 16:47:15.998648

Script ran at 2025-06-18 16:52:10.916605

Script ran at 2025-06-18 17:42:43.328872

Script ran at 2025-06-18 17:45:12.255432

Script ran at 2025-06-18 17:47:16.230254

Script ran at 2025-06-18 17:53:19.224395

Script ran at 2025-06-18 18:00:16.609518

Script ran at 2025-06-18 18:02:31.203034

Script ran at 2025-06-18 18:07:16.606339

Script ran at 2025-06-18 18:15:16.322776

Script ran at 2025-06-18 18:17:18.097467

Script ran at 2025-06-18 18:22:12.097989

Script ran at 2025-06-18 18:30:17.354733

Script ran at 2025-06-18 18:32:23.605211

Script ran at 2025-06-18 18:37:18.729613

Script ran at 2025-06-18 18:45:22.573930

Script ran at 2025-06-18 18:47:17.212886

Script ran at 2025-06-18 20:56:14.297841

Script ran at 2025-06-18 21:00:07.072117

Script ran at 2025-06-18 21:02:15.627273

Script ran at 2025-06-18 21:07:12.793465

Script ran at 2025-06-18 21:09:27.188516

Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Script ran at 2025-06-18 21:45:41.191182

Script ran at 2025-06-18 21:47:39.011279

Script ran at 2025-06-18 21:52:13.287944

Script ran at 2025-06-18 21:54:14.017085

Script ran at 2025-06-18 22:00:07.838247

Script ran at 2025-06-18 22:02:15.442619

Script ran at 2025-06-18 22:07:10.523843

Script ran at 2025-06-18 22:09:10.874735

Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Script ran at 2025-06-19 07:27:33.214415

Script ran at 2025-06-19 07:30:26.424928

Script ran at 2025-06-19 07:34:32.582002

Script ran at 2025-06-19 07:40:30.551849

Error: Failed to fetch prices from API
Script ran at 2025-06-19 09:14:53.431531

Script ran at 2025-06-19 09:15:22.666921

Script ran at 2025-06-19 09:17:18.064930

Script ran at 2025-06-19 09:22:23.259941

Script ran at 2025-06-19 09:24:14.126344

Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Script ran at 2025-06-19 10:17:17.954042

Script ran at 2025-06-19 10:22:12.988688

Script ran at 2025-06-19 10:24:15.079251

Script ran at 2025-06-19 10:30:08.582555

Script ran at 2025-06-19 10:32:15.517756

Script ran at 2025-06-19 10:37:11.591077

Script ran at 2025-06-19 10:39:13.358623

Script ran at 2025-06-19 10:45:22.338610

Script ran at 2025-06-19 10:47:18.048778

Script ran at 2025-06-19 10:52:34.258762

Script ran at 2025-06-19 10:54:17.281854

Script ran at 2025-06-19 11:00:09.500697

Script ran at 2025-06-19 11:02:15.590168

Script ran at 2025-06-19 11:07:10.054190

Script ran at 2025-06-19 11:09:10.294102

Script ran at 2025-06-19 11:15:07.144463

Script ran at 2025-06-19 11:17:16.746345

Script ran at 2025-06-19 11:46:52.367033

Script ran at 2025-06-19 11:47:16.590875

Script ran at 2025-06-19 11:52:42.033939

Script ran at 2025-06-19 11:54:15.350813

Script ran at 2025-06-19 12:05:03.842533

Script ran at 2025-06-19 12:07:14.348418

Script ran at 2025-06-19 12:09:13.889639

Script ran at 2025-06-19 12:15:07.207031

Script ran at 2025-06-19 12:17:18.260553

Script ran at 2025-06-19 12:22:11.102811

Script ran at 2025-06-19 12:24:12.137597

Script ran at 2025-06-19 12:30:09.201131

Script ran at 2025-06-19 12:32:16.177652

Script ran at 2025-06-19 12:37:24.598985

Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Script ran at 2025-06-19 12:47:42.209216

Script ran at 2025-06-19 12:52:12.025510

Script ran at 2025-06-19 12:54:13.878461

Script ran at 2025-06-19 13:00:16.729265

Script ran at 2025-06-19 13:02:31.152037

Script ran at 2025-06-19 13:07:12.555851

Script ran at 2025-06-19 13:09:11.438028

Script ran at 2025-06-19 13:15:07.250833

Script ran at 2025-06-19 13:17:15.724583

Script ran at 2025-06-19 13:22:17.721947

Script ran at 2025-06-19 13:24:34.788116

Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Script ran at 2025-06-19 15:01:12.094709

Script ran at 2025-06-19 15:02:23.359308

Script ran at 2025-06-19 15:07:11.902865

Script ran at 2025-06-19 15:09:12.253481

Script ran at 2025-06-19 15:15:22.115953

Script ran at 2025-06-19 15:17:37.806936

Script ran at 2025-06-19 15:22:48.317741

Error: Failed to fetch prices from API
Script ran at 2025-06-19 15:31:28.383630

Script ran at 2025-06-19 15:32:27.748452

Script ran at 2025-06-19 15:37:20.198004

Script ran at 2025-06-19 15:39:22.162905

Script ran at 2025-06-19 15:45:14.493833

Script ran at 2025-06-19 15:47:28.111584

Script ran at 2025-06-19 15:52:25.121905

Script ran at 2025-06-19 15:54:40.485339

Script ran at 2025-06-19 16:00:15.978790

Script ran at 2025-06-19 16:02:27.196218

Script ran at 2025-06-19 17:13:47.476029

Script ran at 2025-06-19 17:15:26.901093

Script ran at 2025-06-19 17:17:27.203097

Script ran at 2025-06-19 17:22:29.011281

Script ran at 2025-06-19 17:24:33.921483

Script ran at 2025-06-19 17:30:18.753958

Script ran at 2025-06-19 17:32:27.451687

Script ran at 2025-06-19 17:37:14.670794

Script ran at 2025-06-19 17:39:19.483016

Script ran at 2025-06-19 17:45:10.840850

Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Script ran at 2025-06-19 19:22:27.980254

Script ran at 2025-06-19 19:24:13.356331

Script ran at 2025-06-19 19:30:11.079251

Script ran at 2025-06-19 19:32:23.506545

Script ran at 2025-06-19 19:37:26.490955

Error: Failed to fetch prices from API
Script ran at 2025-06-19 19:45:14.411512

Script ran at 2025-06-19 19:47:37.758570

Script ran at 2025-06-19 19:52:12.156632

Script ran at 2025-06-19 19:54:41.839493

Script ran at 2025-06-19 20:00:09.817094

Script ran at 2025-06-19 20:47:24.117066

Script ran at 2025-06-19 20:52:47.116869

Script ran at 2025-06-19 20:54:27.946543

Script ran at 2025-06-19 21:00:10.872744

Script ran at 2025-06-19 21:01:59.428575

Script ran at 2025-06-19 21:02:16.526488

Script ran at 2025-06-19 21:07:39.265550

^CScript ran at 2025-06-19 21:15:15.398299

Script ran at 2025-06-19 21:16:57.373310

Script ran at 2025-06-19 21:17:16.845685

Script ran at 2025-06-19 21:22:13.507339

Script ran at 2025-06-19 21:24:13.024694

Script ran at 2025-06-19 21:30:08.650454

Script ran at 2025-06-19 21:32:07.647799

Script ran at 2025-06-19 21:32:16.070275

Script ran at 2025-06-19 22:17:01.079385

Script ran at 2025-06-19 22:17:24.866457

Script ran at 2025-06-19 22:22:14.735764

Script ran at 2025-06-19 22:24:13.975388

Script ran at 2025-06-19 22:30:12.910897

Script ran at 2025-06-19 22:32:03.279159

Script ran at 2025-06-19 22:32:17.524720

Script ran at 2025-06-19 22:37:15.635931

Script ran at 2025-06-19 22:39:19.090685

Script ran at 2025-06-19 22:45:15.728075

Script ran at 2025-06-19 22:47:00.713337

Script ran at 2025-06-19 22:47:20.142587

Script ran at 2025-06-19 22:52:15.730695

Script ran at 2025-06-19 22:54:18.008112

Script ran at 2025-06-19 23:00:14.334639

Script ran at 2025-06-19 23:01:56.331285

Script ran at 2025-06-19 23:02:20.373712

Script ran at 2025-06-19 23:07:12.133881

Script ran at 2025-06-19 23:09:16.221185

Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Script ran at 2025-06-20 20:37:48.144469

Script ran at 2025-06-20 20:53:07.973487

Script ran at 2025-06-20 21:07:48.868536

Error: Failed to fetch prices from API
Script ran at 2025-06-21 14:52:50.194048

Script ran at 2025-06-21 15:15:04.044986

Script ran at 2025-06-21 15:22:48.815300

Script ran at 2025-06-21 15:44:00.579558

Script ran at 2025-06-21 15:53:11.448793

Script ran at 2025-06-21 16:07:50.363784

Script ran at 2025-06-21 16:41:43.437648

Script ran at 2025-06-21 17:32:57.766102

Script ran at 2025-06-21 17:37:52.313911

Script ran at 2025-06-21 17:53:55.255656

Script ran at 2025-06-21 18:07:58.967505

Script ran at 2025-06-21 18:31:39.048028

Script ran at 2025-06-21 18:40:50.878738

Script ran at 2025-06-21 22:00:36.778240

Script ran at 2025-06-21 22:15:33.058638

Script ran at 2025-06-21 22:30:34.761210

Script ran at 2025-06-21 22:45:34.856539

Script ran at 2025-06-22 20:15:40.901936

Script ran at 2025-06-22 20:35:47.032674

Script ran at 2025-06-22 20:45:26.447077

Script ran at 2025-06-22 21:00:36.768543

Script ran at 2025-06-22 22:06:26.975165

Script ran at 2025-06-22 22:15:15.595532

Script ran at 2025-06-22 23:16:14.105065

Script ran at 2025-06-22 23:30:49.008236

Script ran at 2025-06-22 23:45:43.810101

Script ran at 2025-06-23 00:00:30.893935

Script ran at 2025-06-23 00:16:42.200952

Script ran at 2025-06-23 09:23:22.498494

Script ran at 2025-06-23 09:31:42.077345

Script ran at 2025-06-23 09:45:21.493779

Script ran at 2025-06-23 10:00:17.631585

Script ran at 2025-06-23 10:17:45.845689

Script ran at 2025-06-23 10:30:30.264757

Script ran at 2025-06-23 10:45:16.405775

Script ran at 2025-06-23 11:00:27.664359

Script ran at 2025-06-23 11:15:14.899204

Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Error: Failed to fetch prices from API
Script ran at 2025-06-23 13:31:10.238239

Script ran at 2025-06-23 13:45:19.553977

Script ran at 2025-06-23 14:00:20.732392

Script ran at 2025-06-23 14:15:49.211463

Script ran at 2025-06-23 14:30:50.544256

Script ran at 2025-06-23 14:47:40.661071

Script ran at 2025-06-23 15:55:52.434587

Script ran at 2025-06-23 16:04:58.319938

Script ran at 2025-06-23 16:17:56.307431

Script ran at 2025-06-23 16:30:33.586173

Error: Failed to fetch prices from API
Script ran at 2025-06-23 17:00:41.601707

Script ran at 2025-06-23 17:15:26.563016

Script ran at 2025-06-23 17:35:50.621670

Script ran at 2025-06-23 17:45:49.280032

Script ran at 2025-06-23 18:01:28.226404

Script ran at 2025-06-23 18:15:20.347541

Script ran at 2025-06-23 18:32:05.257485

Script ran at 2025-06-23 18:48:41.212231

